kumuluzee:
  name: comment-management-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/CommentDS
      connection-url: jdbc:postgresql://localhost:5432/comment
      username: dbuser
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/CommentDS
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  metrics:
    web-instrumentation:
      - name: comments-endpoint
        url-pattern: /v1/comments/*
app-properties:
  external-services:
    enabled: true
  healthy: true